config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :credit_pools
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :pages
  resources :transactions
  resources :schools
  resources :meetings, only: [:index, :new, :create, :destroy, :edit, :update]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # routes for recieving credits, the page and the actual transfer route
  get '/users/profile/receive', to: 'users#receive', as: 'user_receive'
  post '/users/profile/do_receive', to: 'users#do_receive', as: 'user_do_receive'

  # Defines the root path route ("/")
  # root "posts#index"

  # route for the actual transfer page
  root to: 'pages#index'

  # action -> controller#action
  get '/users/profile/transfer', to: 'users#transfer', as: 'user-transfer'

  # route for the post request that will be the transfer functionality
  post '/users/profile/transfer/transfer_donor_credits', to: 'users#do_transfer'

  # route for changing user_type
  post '/users/profile/update_user_type', to: 'users#update_user_type', as: 'user_update_type'

  # route to add to the credit pool
  post 'transaction/add_to_pool', to: 'credit_pools#add_to_pool'

  # admin routes
  get '/admin/home', to: 'users#admin_home', as: 'admin-home'
  post '/admin/add_to_pool', to: 'users#admin_add_to_pool'
  post 'admin/subtract_from_pool', to: 'users#admin_subtract_from_pool'


  # oauth stuff
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/auth/failure', to: 'sessions#failure'

  get '/test/login', to: 'sessions#set_session', as: 'test-login'

  get '/users/profile', to: 'users#show', as: 'user-profile'
  get '/users/new', to: 'users#new', as: 'new-user'
  post '/users', to: 'users#create', as: 'create-user'
  get '/users', to: 'users#index', as: 'user-list'
  post '/meetings/:id/accept', to: 'meetings#accept_meeting', as: 'accept-meeting'
  post '/meetings/:id/unaccept', to: 'meetings#unaccept_meeting', as: 'unaccept-meeting'
  post '/meetings/:id/complete', to: 'meetings#complete_transaction', as: 'complete-meeting'
  post '/meetings/:id/donor_cancel', to: 'meetings#donor_cancel', as: 'donor-cancel'

  get '/users/feedback', to: 'users#feedback', as: 'new-feedback'
  post '/users/feedback', to: 'users#submit_feedback', as: 'submit-feedback'
end

app/models/meeting.rb
# frozen_string_literal: true

# class that represents postings for in-person meetings
class Meeting < ApplicationRecord
  before_validation :set_defaults
  validates_presence_of :uid, :date, :time, :location

  private

  def set_defaults
    self.accepted ||= false
    self.accepted_uid ||= nil
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

# controller class for meetings
class MeetingsController < ApplicationController
  before_action :set_uid, only: %i[new create]
  helper_method :get_this_week

  def index
    @meetings = Meeting.where(accepted: false)
    @user = User.find(session[:user_id])
    @current_uid = current_user.uid
    @user_meetings = Meeting.where(accepted: true).where('uid = ? OR accepted_uid = ?', @current_uid, @current_uid)
  end

  def new
    @meeting = Meeting.new(uid: @current_uid)
  end

  def create
    @user = User.find(session[:user_id])
    @current_uid = current_user.uid
    @meeting = Meeting.new(meeting_params.merge(uid: @current_uid, accepted: false))

    if @meeting.save

      redirect_to meetings_path, notice: 'Meeting scheduled successfully.'
    else
      logger.error "NOT SCHEDULED: #{@meeting}"
      logger.error "Validation errors: #{@meeting.errors.full_messages}"

      render :new
    end
  end

  def edit
    @user = User.find(session[:user_id])
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
  end

  def update
    @meeting = Meeting.find_by(id: params[:id])
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to '/meetings', notice: 'Your meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
    if @meeting
      if @meeting.destroy
        redirect_to meetings_path, notice: 'Meeting deleted successfully.'
      else
        redirect_to meetings_path, notice: 'Error: Meeting not deleted.'
      end
    else
      redirect_to meetings_path, notice: 'Error: Meeting not found.'
    end
  end

  def accept_meeting
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
    return unless @meeting

    @meeting.update(accepted: true, accepted_uid: @current_uid)
    redirect_to meetings_path, notice: 'Meeting accepted.'
  end

  def unaccept_meeting
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
    return unless @meeting

    @meeting.update(accepted: false, accepted_uid: nil)
    redirect_to meetings_path, notice: 'Meeting unaccepted.'
  end

  def get_next_week(id)
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id:)
    original_date = @meeting.date
    @date = original_date + 7
  end

  def complete_transaction
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
    if @meeting.recurring
      @meeting.update(date: get_next_week(@meeting.id), accepted: false, accepted_uid: nil)
    else
      @meeting.destroy
    end
    redirect_to meetings_path, notice: 'Meeting Completed.'
  end

  def donor_cancel
    @current_uid = current_user.uid
    @meeting = Meeting.find_by(id: params[:id])
    if @meeting.recurring == true
      @meeting.update(accepted: false, accepted_uid: nil)
      redirect_to meetings_path, notice: 'Meeting cancelled. Recurring meeting posted.'
    else
      @meeting.destroy
      redirect_to meetings_path, notice: 'Meeting cancelled.'
    end
  end

  private

  def set_uid
    @current_user = User.find(session[:user_id])
    @current_uid = current_user.uid
  end

  def meeting_params
    params.require(:meeting).permit(:date, :time, :location, :recurring, :accepted)
  end
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

# module for Meeting Helper
module MeetingsHelper
end

app/views/meetings/edit.html.erb
<h1>Edit a Meeting</h1>
<%= form_with url: @meeting, method: :patch do |f| %>
  <div>
    <%= label :meeting, :date, 'Date' %>
    <%= date_field :meeting, :date, value: @meeting.date %>
  </div>
  <div>
    <%= label :meeting, :time, 'Time' %>
    <%= time_field :meeting, :time, value: @meeting.time %>
  </div>
  <div>
  <%= label :meeting, :location, 'Location' %>
  <%= text_field :meeting, :location, value: @meeting.location %>
  </div>
  <div>
  <%= label :meeting, :recurring, 'Recurring' %>
  <%= check_box :meeting, :recurring, value: @meeting.recurring %>
  </div>
  <%= f.hidden_field :accepted, value: false %>
  <div>
    <%= f.submit 'Confirm Changes' %>
  </div>
<% end %>

app/views/meetings/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Transactions</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag "transactions" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>
</head>
<body>
  <div class="outerDiv">
    <p class="title">Meetings</p>
    <% if @user.user_type == "donor" %>
      <div style="margin: 50px 0;">
        <%= link_to 'Schedule a Meeting', new_meeting_path, class: 'actionBtn' %>
      </div>
    <% end %>
    <p class="char">
      Public Meetings
    </p>

    <div style="margin: 30px 0;">
      <table class="transTable" id="publicMeetingsTable">
        <thead class="thead-dark">
          <tr>
            <th class="text-center">Posted by</th>
            <th class="text-center">Time</th>
            <th class="text-center">Date</th>
            <th class="text-center">Location</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>
          <% if @meetings.present? %>
            <% @meetings.each do |meeting| %>
              <tr class='meeting-item'>
                <td><%= meeting.uid %></td>
                <td><%= meeting.time.strftime("%I:%M %p") %></td>
                <td>
                    <%= meeting.date.strftime("%a %m/%d/%Y") %>
                </td>
                <td><%= meeting.location %></td>
                <% if meeting.uid == @current_uid %>
                  <td>
                    <%= button_to 'Edit', "/meetings/#{meeting.id}/edit", method: :get, class: 'actionBtn' %>
                    <%= button_to 'Cancel', "/meetings/#{meeting.id}", method: :delete, class: 'actionBtn' %>
                  </td>
                <% end %>
                <% if @user.user_type == "recipient" %>
                  <td><%= button_to "Accept", accept_meeting_path(id: meeting.id), class: 'actionBtn' %></td>
                <% end %>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="7">No public meetings.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <p class="char">
      Your Meetings
    </p>

    <div style="margin: 20px 0;">
      <table class="transTable" id="yourMeetingsTable">
        <thead class="thead-dark">
          <tr>
            <th class="text-center">Posted by</th>
            <th class="text-center">Accepted By</th>
            <th class="text-center">Time</th>
            <th class="text-center">Date</th>
            <th class="text-center">Location</th>
            <th class="text-center">Cancel</th>
            <th class="text-center">Complete</th>
          </tr>
        </thead>
        <tbody>
          <% if @user_meetings.present? %>
            <% @user_meetings.each do |meeting| %>
              <tr class='meeting-item'>
                <td><%= meeting.uid %></td>
                <td><%= meeting.accepted_uid %></td>
                <td><%= meeting.time.strftime("%I:%M %p") %></td>
                <td><%= meeting.date.strftime("%a %m/%d/%Y") %></td>
                <td><%= meeting.location %></td>
                <td>
                  <% if meeting.uid == @current_uid && @user.user_type == 'donor' %>
                    <%# donor button %>
                    <%= button_to 'Cancel', donor_cancel_path(meeting.id), class: 'actionBtn' %>
                  <% end %>
                  <% if meeting.accepted_uid == @current_uid && @user.user_type == 'recipient' %>
                    <%# recipient button %>
                    <%= button_to 'Cancel', unaccept_meeting_path(id: meeting.id), class: 'actionBtn' %>
                  <% end %>
                </td>
                <td>
                  <%= button_to "Done", complete_meeting_path(id: meeting.id), class: 'actionBtn' %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="7">No meetings scheduled.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/meetings/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Schedule a Meeting</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag "profile" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>
  <style>
    body {
      background-color: #F4EDE5;
    }

    h1 {
      font-family: "Protest Riot", sans-serif;
      font-size: 50px;
      color: #E3686C;
      text-align: center;
      margin-bottom: 25px;
    }

    form {
      text-align: center;
    }

    form-group {
      margin-bottom: 20px;
    }

    input[type="text"],
    input[type="date"],
    input[type="time"],
    input[type="submit"],
    input[type="checkbox"] {
      flex-direction: column;
      align-items: center;
      text-align: center;
      justify-content: space-between;
      display: flex;
      margin: 10px auto;
      padding: 10px;
      width: 20%;
      height: 50%;
    }

    input[type="submit"] {
      background-color: #E8B1B0;
      color: black;
      border: none;
      border-radius: 5px;
      font-family: "Quicksand", sans-serif;
      font-size: 14px;
      font-weight: 800;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
      background-color: #E3686C;
      color: black;
    }
  </style>
</head>
<body>
  <div class="outerBack">
    <a href="<%= meetings_path %>" class="back-button">&lt;</a>
  </div>
  <h1>Schedule a Meeting</h1>
  <%= form_for @meeting do |f| %>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>
    <div class="form-group">
      <%= f.label :time %>
      <%= f.time_field :time %>
    </div>
    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class="form-group">
      <%= f.label :recurring %>
      <%= f.check_box :recurring, id: "newRecurring" %>
    </div>
    <%= f.hidden_field :accepted, value: false %>
    <div class="form-group">
      <%= f.submit 'Schedule Meeting' %>
    </div>
  <% end %>
</body>
</html>