config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :credit_pools
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :pages
  resources :transactions
  resources :schools
  resources :meetings, only: [:index, :new, :create, :destroy, :edit, :update]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # routes for recieving credits, the page and the actual transfer route
  get '/users/profile/receive', to: 'users#receive', as: 'user_receive'
  post '/users/profile/do_receive', to: 'users#do_receive', as: 'user_do_receive'

  # Defines the root path route ("/")
  # root "posts#index"

  # route for the actual transfer page
  root to: 'pages#index'

  # action -> controller#action
  get '/users/profile/transfer', to: 'users#transfer', as: 'user-transfer'

  # route for the post request that will be the transfer functionality
  post '/users/profile/transfer/transfer_donor_credits', to: 'users#do_transfer'

  # route for changing user_type
  post '/users/profile/update_user_type', to: 'users#update_user_type', as: 'user_update_type'

  # route to add to the credit pool
  post 'transaction/add_to_pool', to: 'credit_pools#add_to_pool'

  # admin routes
  get '/admin/home', to: 'users#admin_home', as: 'admin-home'
  post '/admin/add_to_pool', to: 'users#admin_add_to_pool'
  post 'admin/subtract_from_pool', to: 'users#admin_subtract_from_pool'


  # oauth stuff
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/auth/failure', to: 'sessions#failure'

  get '/test/login', to: 'sessions#set_session', as: 'test-login'

  get '/users/profile', to: 'users#show', as: 'user-profile'
  get '/users/new', to: 'users#new', as: 'new-user'
  post '/users', to: 'users#create', as: 'create-user'
  get '/users', to: 'users#index', as: 'user-list'
  post '/meetings/:id/accept', to: 'meetings#accept_meeting', as: 'accept-meeting'
  post '/meetings/:id/unaccept', to: 'meetings#unaccept_meeting', as: 'unaccept-meeting'
  post '/meetings/:id/complete', to: 'meetings#complete_transaction', as: 'complete-meeting'
  post '/meetings/:id/donor_cancel', to: 'meetings#donor_cancel', as: 'donor-cancel'

  get '/users/feedback', to: 'users#feedback', as: 'new-feedback'
  post '/users/feedback', to: 'users#submit_feedback', as: 'submit-feedback'
end

app/models/credit_pool.rb
# frozen_string_literal: true

# class that represents the pool of donated credits available
class CreditPool < ApplicationRecord
  validates :credits, presence: true

  def add_credits(amt)
    update(credits: credits + amt)
  end

  def subtract_credits(amt)
    raise StandardError, 'Not enough credits to subtract this amount' if amt > credits

    update(credits: credits - amt)
  end
end

app/controllers/credit_pools_controller.rb
# frozen_string_literal: true

# controller class for CreditPools
class CreditPoolsController < ApplicationController
  before_action :set_credit_pool, only: %i[show edit update destroy]

  # GET /credit_pools or /credit_pools.json
  def index
    @credit_pools = CreditPool.all
    @types = %w[donated received]
    @credit_pool = CreditPool.find_by(school_name: 'TAMU')
  end

  # GET /credit_pools/1 or /credit_pools/1.json
  def show
    @credit_pool = CreditPool.find(params[:id])
    @types = %w[donated received]
    @user = User.find(session[:user_id])
  end

  # GET /credit_pools/new
  def new; end

  # GET /credit_pools/1/edit
  def edit
    @credit_pool = CreditPool.find(params[:id])
  end

  # POST /credit_pools or /credit_pools.json
  def create
    @credit_pool = CreditPool.create!(credit_pool_params)

    flash[:notice] = "#{@credit_pool.school_name}'s credit pool was successfully created."
    redirect_to credit_pools_path
    # respond_to do |format|
    #   if @credit_pool.save
    #     format.html { redirect_to credit_pool_url(@credit_pool), notice: 'Credit pool was successfully created.' }
    #     format.json { render :show, status: :created, location: @credit_pool }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @credit_pool.errors, status: :unprocessable_entity }
    #   end
    # end
  rescue StandardError
    flash[:warning] = 'Credit Pool Creation Failed'
    redirect_to '/', alert: 'Login failed.'
  end

  # PATCH/PUT /credit_pools/1 or /credit_pools/1.json
  def update
    respond_to do |format|
      if @credit_pool.update(credit_pool_params)
        format.html do
          redirect_to credit_pool_url(@credit_pool),
                      notice: "#{@credit_pool.school_name}'s credit pool was successfully updated."
        end
        format.json { render :show, status: :ok, location: @credit_pool }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_pools/1 or /credit_pools/1.json
  def destroy
    name = @credit_pool.school_name
    @credit_pool.destroy!

    respond_to do |format|
      format.html { redirect_to credit_pools_url, notice: "#{name}'s credit pool was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_credit_pool
    @credit_pool = CreditPool.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def credit_pool_params
    params.require(:credit_pools).permit(:school_name, :credits, :email_suffix, :id_name, :logo_url)
  end
end

app/helpers/credit_pools_helper.rb
# frozen_string_literal: true

# helper module for the CreditPools class
module CreditPoolsHelper
end

app/views/credit_pools/_credit_pool.html.erb
<div class="card text-white bg-dark m-2 p-0" style="width: 18rem; height: 30rem" id="<%= dom_id credit_pool %>">
  <div  class="card-body">
    <h5 class="card-title"><%= credit_pool.school_name %></h5>
    <p class="card-text">
      <strong>Credits:</strong>
      <%= credit_pool.credits %>
    </p>
    <div class="mb-1">
      <%= link_to "Details", credit_pool_path(credit_pool), class: 'btn btn-outline-light mb-1' %>
    </div>
  </div>
  <img class="card-img-bottom" src="<%= credit_pool.logo_url %>">
</div>

app/views/credit_pools/_form.html.erb
<%= form_with(model: credit_pool) do |form| %>
  <% if credit_pool.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(credit_pool.errors.count, "error") %> prohibited this credit_pool from being saved:</h2>

      <ul>
        <% credit_pool.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :credits, style: "display: block" %>
    <%= form.number_field :credits %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_pools/edit.html.erb
<h1>Edit <%= @credit_pool.school_name %> Credit Pool</h1>

<%= form_with url: @credit_pool, method: :patch do |f| %>
  <%= label :credit_pools, :school_name, 'School Name', :class => 'col-form-label' %>
  <%= text_field :credit_pools, :school_name, value: @credit_pool.school_name, :class => 'form-control' %>
  <%= label :credit_pools, :credits, 'Credits', :class => 'col-form-label'  %>
  <%= number_field :credit_pools, :credits, value: @credit_pool.credits, :class => 'form-control' %>
  <%= label :credit_pools, :email_suffix, 'Email Suffix', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :email_suffix, value: @credit_pool.email_suffix, :class => 'form-control' %>
  <%= label :credit_pools, :id_name, 'ID Alias', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :id_name, value: @credit_pool.id_name, :class => 'form-control' %>
  <%= label :credit_pools, :logo_url, 'URL to Logo', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :logo_url, value: @credit_pool.logo_url, :class => 'form-control' %>

  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', credit_pool_path(@credit_pool), :class => 'btn btn-secondary' %>
<% end %>

app/views/credit_pools/index.html.erb
<h1>Credit pools</h1>

<div class="container">
  <div class="row">
    <% @credit_pools.each do |credit_pool| %>
      <%= render credit_pool %>
    <% end %>
  </div>
</div>

<div style="margin-top: 5px">
  <%= link_to "New Credit Pool", new_credit_pool_path, class: 'btn btn-primary' %>
</div>

app/views/credit_pools/new.html.erb
<h1>Create New Credit Pool</h1>

<%= form_with url: '/credit_pools', method: :post do |f| %>
  <%= label :credit_pools, :school_name, 'School Name', :class => 'col-form-label' %>
  <%= text_field :credit_pools, :school_name, :class => 'form-control' %>
  <%= label :credit_pools, :credits, 'Credits', :class => 'col-form-label'  %>
  <%= number_field :credit_pools, :credits, :class => 'form-control' %>
  <%= label :credit_pools, :email_suffix, 'Email Suffix', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :email_suffix, :class => 'form-control' %>
  <%= label :credit_pools, :id_name, 'ID Alias', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :id_name, :class => 'form-control' %>
  <%= label :credit_pools, :logo_url, 'URL to Logo', :class => 'col-form-label'  %>
  <%= text_field :credit_pools, :logo_url, :class => 'form-control' %>

  <br/>
  <%= submit_tag 'Create Credit Pool', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', credit_pools_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/credit_pools/show.html.erb
<h1>
  <strong>School Name:</strong>
  <%= @credit_pool.school_name %>
</h1>
<p>
  <strong>Credits:</strong>
  <%= @credit_pool.credits %>
</p>
<p>
  <strong>Email Suffix:</strong>
  <%= @credit_pool.email_suffix %>
</p>
<p>
  <strong>ID Alias:</strong>
  <%= @credit_pool.id_name %>
</p>
<p><strong>Logo:</strong></p>
<div>
  <img src="<%= @credit_pool.logo_url %>" style="max-width:100px;width:100%">
</div>
<%= line_chart @types.map { |type|
    {name: type, data: Transaction.where(transaction_type: type, credit_pool_id: @credit_pool.id).group_by_day(:created_at).sum(:amount)}
    }, id: "#{@credit_pool.school_name}Chart", discrete: true, xTitle: "Date", yTitle: "Amount"
%>
<div class="mt-2" style="display:flex">
  <%= button_to "Edit Credit Pool", edit_credit_pool_path(id: @credit_pool.id), method: :get,  class: 'btn btn-primary' %>
  <%= button_to "Destory Credit Pool", @credit_pool, method: :delete, class: 'btn btn-danger ml-1' %>
</div>

<%= link_to "Back to credit pools", credit_pools_path, class: 'btn btn-primary mt-2' %>
<% if @user.admin %>
  <%= link_to "Back to Admin Dashboard", admin_home_path, class: 'btn btn-primary mt-2' %>
<% end %>