config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :credit_pools
  get 'sessions/logout'
  get 'sessions/omniauth'

  resources :pages
  resources :transactions
  resources :schools
  resources :meetings, only: [:index, :new, :create, :destroy, :edit, :update]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # routes for recieving credits, the page and the actual transfer route
  get '/users/profile/receive', to: 'users#receive', as: 'user_receive'
  post '/users/profile/do_receive', to: 'users#do_receive', as: 'user_do_receive'

  # Defines the root path route ("/")
  # root "posts#index"

  # route for the actual transfer page
  root to: 'pages#index'

  # action -> controller#action
  get '/users/profile/transfer', to: 'users#transfer', as: 'user-transfer'

  # route for the post request that will be the transfer functionality
  post '/users/profile/transfer/transfer_donor_credits', to: 'users#do_transfer'

  # route for changing user_type
  post '/users/profile/update_user_type', to: 'users#update_user_type', as: 'user_update_type'

  # route to add to the credit pool
  post 'transaction/add_to_pool', to: 'credit_pools#add_to_pool'

  # admin routes
  get '/admin/home', to: 'users#admin_home', as: 'admin-home'
  post '/admin/add_to_pool', to: 'users#admin_add_to_pool'
  post 'admin/subtract_from_pool', to: 'users#admin_subtract_from_pool'


  # oauth stuff
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/auth/failure', to: 'sessions#failure'

  get '/test/login', to: 'sessions#set_session', as: 'test-login'

  get '/users/profile', to: 'users#show', as: 'user-profile'
  get '/users/new', to: 'users#new', as: 'new-user'
  post '/users', to: 'users#create', as: 'create-user'
  get '/users', to: 'users#index', as: 'user-list'
  post '/meetings/:id/accept', to: 'meetings#accept_meeting', as: 'accept-meeting'
  post '/meetings/:id/unaccept', to: 'meetings#unaccept_meeting', as: 'unaccept-meeting'
  post '/meetings/:id/complete', to: 'meetings#complete_transaction', as: 'complete-meeting'
  post '/meetings/:id/donor_cancel', to: 'meetings#donor_cancel', as: 'donor-cancel'

  get '/users/feedback', to: 'users#feedback', as: 'new-feedback'
  post '/users/feedback', to: 'users#submit_feedback', as: 'submit-feedback'
end

app/models/user.rb
# frozen_string_literal: true

require 'net/http'

# Class that represents a user of the app
class User < ApplicationRecord
  validates :uid, :name, :email, :user_type, presence: true
  attribute :admin, :boolean, default: false

  def fetch_num_credits
    uri = URI("https://tamu-dining-62fbd726fd19.herokuapp.com/users/#{uid}")
    res = Net::HTTP.get(uri)
    json_res = JSON.parse(res)
    json_res['credits']
  end

  def update_credits(amount)
    uri = URI("https://tamu-dining-62fbd726fd19.herokuapp.com/users/#{uid}/update_credits/#{amount}")

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = (uri.scheme == 'https')

    request = Net::HTTP::Patch.new(uri.request_uri)
    response = http.request(request)

    # if (response.code.to_i != 200)
    #   puts "The response is #{response}"
    #   puts "response code is #{response.code}"
    # end

    fetch_num_credits

    response
  end

  def set_admin
    uri = URI("https://tamu-dining-62fbd726fd19.herokuapp.com/administrators/#{email}/validate_admin")
    res = Net::HTTP.get(uri)
    json_res = JSON.parse(res)
    if json_res == true
      update(admin: true)
    else
      update(admin: false)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

$user_request_limit = 10

# controller class for Users
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_admin, only: %i[admin_home admin_add_to_pool admin_subtract_from_pool]

  # ----------- admin specific controller methods ---------------

  def authenticate_admin
    @user = User.find(session[:user_id])
    return unless !@user || !@user.admin

    flash[:notice] = 'You are not authorized to access this page.'
    redirect_to root_path
  end

  def admin_home
    @user = User.find(session[:user_id])
    pool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    @id_name = pool.presence ? pool.id_name : 'ID'
    @user_school = pool
  end

  def admin_add_to_pool
    # check to make value is an integer
    unless params[:credits].to_i.to_s == params[:credits]
      flash[:warning] = 'ERROR Invalid input!'
      redirect_to :admin_home
      return
    end

    num_credits = params[:credits].to_i
    @user = User.find(session[:user_id])

    if num_credits.zero? || num_credits.negative?
      flash[:warning] = 'ERROR Invalid input!'
      redirect_to :admin_home
      return
    end

    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    @creditpool.add_credits(num_credits)

    flash[:notice] = "CONFIRMATION Successfully added #{num_credits} credits to the pool!"
    redirect_to :admin_home
  end

  def admin_subtract_from_pool
    # check to make value is an integer
    unless params[:credits].to_i.to_s == params[:credits]
      flash[:warning] = 'ERROR Invalid input!'
      redirect_to :admin_home
      return
    end

    num_credits = params[:credits].to_i
    @user = User.find(session[:user_id])

    if num_credits.zero? || num_credits.negative?
      flash[:warning] = 'ERROR Invalid input!'
      redirect_to :admin_home
      return
    end

    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)

    if num_credits > @creditpool.credits
      flash[:warning] =
        "Can't subtract more credits than there are available, only #{@creditpool.credits} credits currently in pool"
      redirect_to :admin_home
      return
    end

    @creditpool.subtract_credits(num_credits)
    flash[:notice] = "CONFIRMATION Successfully subtracted #{num_credits} credits from the pool!"
    redirect_to :admin_home
  end

  # ----------- end of admin controller methods ---------------

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
    pool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    @id_name = pool.presence ? pool.id_name : 'ID'
    @user_school = pool
  end

  def new
    pool = CreditPool.find_by(email_suffix: session[:email].partition('@').last)
    @id_name = pool.presence ? pool.id_name : 'ID'
  end

  def edit; end

  def create
    new_params = new_user_params
    user_info = get_user_info new_params['uid']
    if user_info.key?('error')
      raise 'Error has occurred'
    elsif user_info['email'] != session[:email]
      pool = CreditPool.find_by(email_suffix: session[:email].partition('@').last)
      id_name = pool.presence ? pool.id_name : 'ID'
      raise "Email does not match the #{id_name}"
    elsif (new_params['user_type'] == 'recipient') && (user_info['credits'] > $user_request_limit)
      raise 'User has too many credits to create a receipent account'
    end

    # needs to change this after updating the external api, just the uin part
    @user = User.create!({ uid: user_info['uin'], name: "#{user_info['first_name']} #{user_info['last_name']}",
                           email: user_info['email'], user_type: new_params['user_type'], credits: 0 })
    flash[:notice] = %(#{@user.name}'s account was successfully created.)
    session[:user_id] = @user.id
    session.delete('email')
    redirect_to '/users/profile'
  rescue StandardError => e
    flash[:notice] = e.message
    redirect_to '/', alert: 'Login failed.'
  end

  def update; end

  def search; end

  def transfer
    # this is the controller for the actual transfer page
    # all we really want to do is set the global uid and user so we can use it later when we make our transfer call
    @user = User.find_by(id: session[:user_id])

    # puts "params #{params}"
    # puts @user.name
    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    # puts "credit pool: #{@creditpool}"
  end

  def do_transfer
    # puts "INITIATING TRANSFER!"
    # grab who is doing the transfer, and how much

    unless params[:credits].to_i.to_s == params[:credits]
      flash[:notice] = 'ERROR Invalid input!'
      redirect_to :user_transfer
      return
    end
    num_credits = params[:credits].to_i
    id = session[:user_id]
    # puts "params: #{params}"
    # puts "uid #{params[:id]} is sending #{params[:credits]} credits to the pool"
    @user = User.find_by(id:)

    # check to see if there are any errors with credit amount
    if num_credits > @user.fetch_num_credits
      flash[:notice] = 'ERROR Trying to donate more credits than you have!'
      redirect_to :user_transfer
      return

    end

    if num_credits.zero? || num_credits.negative?
      flash[:notice] = 'ERROR Invalid input!'
      redirect_to :user_transfer
      return
    end

    # now, subtract credits from their account
    response = @user.update_credits(-1 * num_credits)

    # handles bad update_credit api call
    if response.code.to_i / 100 == 2
      # puts "Credit update successful"
    else
      flash[:warning] = "Error updating credits. Status code: #{response.code}"
      redirect_to :user_transfer
      return -1
    end

    # send the number of transfered credits to the pool TODO: DRY above in page_load (session maybe?)
    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)

    # create a transaction object
    Transaction.create({ uid: @user.uid, transaction_type: 'donated', amount: num_credits,
                         credit_pool_id: @creditpool.id })

    @creditpool.add_credits(num_credits)

    # notify user it's successful somehow
    flash[:notice] = "CONFIRMATION Sucessfully donated #{num_credits} credits to the pool!"
    redirect_to :user_transfer
  end

  def receive
    @user = User.find_by(id: session[:user_id])
    @uid = @user.uid
    # puts "CREDIT POOL: " + @user.email.partition('@').last
    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    # puts "ACTUAL: " + CreditPool.all.length.to_s
  end

  def do_receive
    @user = User.find_by(id: session[:user_id])
    num_credits = params[:num_credits].to_i
    user_credits = @user.fetch_num_credits

    # handles invalid number of credits
    if num_credits <= 0
      flash[:notice] = 'ERROR Invalid input!'
      redirect_to :user_receive
      return -1
    end

    if user_credits >= $user_request_limit
      flash[:warning] = "Must have less than #{$user_request_limit} credits in order to make a request"
      redirect_to :user_receive
      return -1
    end

    @creditpool = CreditPool.find_by(email_suffix: @user.email.partition('@').last)
    # handles there not being enough credits for the request
    if num_credits > @creditpool.credits
      flash[:warning] = "Not enough credits available, only #{@creditpool.credits} credits currently in pool"
      redirect_to :user_receive
      return -1
    end

    if num_credits > $user_request_limit
      flash[:warning] = "Request too large, maximum allowed per request is #{$user_request_limit} credits"
      redirect_to :user_receive
      return -1
    end

    response = @user.update_credits(num_credits)

    # handles bad response from update_credit api call
    if response.code.to_i / 100 > 2
      flash[:warning] = "Error updating credits. Status code: #{response.code}"
      redirect_to :user_receive
      return -1
    end

    @creditpool.subtract_credits(num_credits)
    Transaction.create({ uid: @user.uid, transaction_type: 'received', amount: num_credits,
                         credit_pool_id: @creditpool.id })

    # notify user it's successful somehow
    flash[:notice] = "CONFIRMATION Sucessfully recieved #{num_credits} credits!"
    redirect_to :user_receive
  end

  def update_user_type
    @user = User.find_by(id: session[:user_id])
    new_user_type = params[:new_user_type]

    if (new_user_type != 'recipient') && (new_user_type != 'donor')
      flash[:warning] = "Error, invalid user type. User type must be 'donor' or 'recipient'"
      redirect_to :user_profile
      return -1
    end

    if (new_user_type == 'recipient') && (@user.fetch_num_credits > $user_request_limit)
      flash[:warning] = 'Too many credits to be a recipient'
      redirect_to :user_profile
      return
    end

    @user.update({ user_type: new_user_type })

    if @user.user_type == new_user_type
      flash[:notice] = "Type successfully updated to #{new_user_type}"
    else
      flash[:warning] = "Error updating user type to #{new_user_type}"
    end
    redirect_to :user_profile
  end

  def feedback
    @user = User.find_by(id: session[:user_id])
  end

  def submit_feedback
    @user = User.find_by(id: session[:user_id])
    ApplicationMailer.with(user: @user, feedback: params[:feedback]).feedback_email.deliver_now
    flash[:notice] = 'Feedback sent!'
    redirect_to :user_profile
  end

  private

  def new_user_params
    params.require(:user).permit(:uid, :user_type)
  end

  def get_user_info(uid)
    uri = URI("https://tamu-dining-62fbd726fd19.herokuapp.com/users/#{uid}")
    JSON.parse(Net::HTTP.get(uri))
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# helper module for the User class
module UsersHelper
end

app/views/users/admin_home.html.erb
<%= stylesheet_link_tag "profile" %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>

<div class="outerDiv">
  <div id="user-details">
    <div class="titleDiv">
      <p class="title">Admin Dashboard</p>
    </div>

    <div class="charDiv">
      <p class="char">
        <strong>Name:</strong>
        <%= @user.name %>
      </p>
    </div>

    <div class="charDiv">
      <p class="char">
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
    </div>

    <div class="charDiv">
      <p class="char">
        <strong>School:</strong>
        <%= @user_school.school_name %>
      </p>
    </div>

    <div class="charDiv">
      <p class="char">
        <strong>Credits in Pool:</strong>
        <%= @user_school.credits %>
      </p>
    </div>


    <form method='post'>
        <label for='credit-amount' class='char'>Update Credits in Pool: </label>
        <input type="number" step="1" min="1" id='credit-amount' class="margin-input" name="credits"/>
        <input name="credit-pool-add" type="submit" class="submit" value="Add Credits" formaction="/admin/add_to_pool"/>
        <input name="credit-pool-subtract" type="submit" class="submit" value="Subtract Credits" formaction="/admin/subtract_from_pool"/>
    </form>

    <div class="row mt-3 justify-content-center">
      <div class="col-auto mb-2">
        <%= button_to "View Credit Pool", credit_pool_path(@user_school.id), method: :get, class: "btn actionBtn" %>
      </div>
      <div class="col-auto">
        <%= button_to "Log Out", logout_path, method: :get, class: "btn actionBtn" %>
      </div>
  </div>

  <% if @user_school.present? && @user_school.logo_url.present? %>
    <div class="row mt-5">
      <div class="col-md-6 offset-md-3">
        <div class="text-center">
          <%= image_tag @user_school.logo_url, class: "school-logo" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/feedback.html.erb
<%= stylesheet_link_tag "profile" %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>

<div class="outerDiv">
  <div class="outerBack">
    <a href="<%= user_profile_path %>" class="back-button">&lt;</a>
  </div>
  <div id="user-details">
    <div class="titleDiv">
      <p class="title">Feedback</p>
    </div>
  </div>
  
  <form action="/users/feedback" method='post'>
    <textarea type="text" id='feedback' class="margin-input" style="width: 500px; height: 200px" name="feedback"> </textarea>
    <div>
      <input name="feedback-submission" type="submit" class="actionBtn" value="Submit Feedback" />
    </div>
  </form>
</div>

app/views/users/get_credits.html.erb
<div>
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>UIN:</strong>
    <%= @user.uin %>
  </p>

  <p>
    <strong>Credits:</strong>
    <%= @user.credits %>
  </p>

</div>

app/views/users/index.html.erb
<h2>All Users</h2>

<table class="table table-striped col-md-12" id="users">
  <thead>
    <tr>
      <th><%= @id_name %></th>
      <th>Name</th>
      <th>Email</th>
      <th>Date Joined</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.uid %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.date_joined %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h2>Create New User</h2>

<%= form_with url: '/users', method: :post do |f| %>
  <%= label :user, :uid, @id_name, :class => 'col-form-label' %>
  <%= text_field :user, :uid, :class => 'form-control' %>
  <%= label :user, :user_type, 'User Type*', :class => 'col-form-label'  %>
  <%= select :user, :user_type, ['donor', 'recipient'], {}, :class => 'form-control' %>
  <p>*You need to have 10 or less credit to qualify for a recipient account</p>

  <br/>
  <%= submit_tag 'Create Account', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', root_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/users/receive.html.erb
<%= stylesheet_link_tag "transfer" %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>

<div class='outerDiv'>
    <div class='heading'>
        <p class="title">Request Credits</p>
        <p class="char">Request meal credits from the donated pool!</p>
        <p class="char-center">User Credits: <%=@user.fetch_num_credits%></p>
        <p class="char-center">Pool Credits: <%=@creditpool.credits%></p>
    </div>
    <div class="creditDiv">
        <form action="/users/profile/do_receive" method='post'>
            <label for='credit-amount'>Enter a credit amount: </label>
            <input id='credit-amount' class="margin-input" name="num_credits"/>
            <input name="credit-submission" type="submit" class="submit" value="Request" />
        </form>
    </div>
</div>

app/views/users/search.html.erb
<h1>Users#search</h1>
<p>Find me in app/views/users/search.html.erb</p>

app/views/users/show.html.erb
<%= stylesheet_link_tag "profile" %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="outerDiv">
        <div id="user-details">
          <div class="titleDiv">
            <p class="title"><% if @user.admin %>Administrator<% else %>User<% end %> Profile</p>
          </div>

          <div class="charDiv">
            <p class="char">
              <strong>Name:</strong>
              <%= @user.name %>
            </p>
          </div>

          <div class="charDiv">
            <p class="char">
              <strong>Email:</strong>
              <%= @user.email %>
            </p>
          </div>

          <div class="charDiv">
            <p class="char">
              <strong><%= @id_name %>:</strong>
              <%= @user.uid %>
            </p>
          </div>

          <div class="charDiv">
            <p class="char">
              <strong>Credits:</strong>
              <%= @user.fetch_num_credits %>
            </p>
          </div>

          <div class="charDiv">
            <p class="char">
              <strong>Type:</strong>
              <%= @user.user_type %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-4 offset-md-4">
      <div class="d-flex justify-content-between">
        <%= form_with url: :user_update_type, method: :post, data: { turbo_action: "replace", turbo_frame: "user-details" } do |form| %>
          <% if @user.user_type == "donor" %>
              <%= form.hidden_field :new_user_type, value: "recipient" %>
              <%= form.submit "Change to Recipient", class: "actionBtn", data: { turbo_confirm: "Are you sure you want to change account types?" } %>
          <% else %>  
            <%= form.hidden_field :new_user_type, value: "donor" %>
            <%= form.submit "Change to Donor", class: "actionBtn", data: { turbo_confirm: "Are you sure you want to change account types?" } %>
          <% end %>
        <% end %>
        
        
        <%= button_to "Give Feedback", new_feedback_path, :method => :get, class: "actionBtn" %>
        <%= button_to "Log Out", logout_path, :method => :get, class: "actionBtn" %>
      </div>
    </div>
  </div>

  <% if @user.admin %>
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <%= button_to "Go To Admin Dashboard", admin_home_path, :method => :get, class: "actionBtn" %>
      </div>
    <div>
  <% end %>

  <% if @user_school.present? && @user_school.logo_url.present? %>
    <div class="row mt-5">
      <div class="col-md-6 offset-md-3">
        <div class="text-center">
          <%= image_tag @user_school.logo_url, class: "school-logo" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/transfer.html.erb
<%= stylesheet_link_tag "transfer" %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Protest+Riot&family=Quicksand:wght@300..700&display=swap", media: 'all' %>

<div class='outerDiv'>
    <div class='heading'>
        <p class="title">Transfer Credits</p>
        <p class="char">Donate meal credits to the pool today!</p>
        <p class="char-center">User Credits: <%=@user.fetch_num_credits%></p>
        <p class="char-center">Pool Credits: <%=@creditpool.credits%></p>
    </div>
    <div class="creditDiv">
        <form action="/users/profile/transfer/transfer_donor_credits" method='post'>
            <label for='credit-amount'>Enter a credit amount: </label>
            <input type="number" step="1" min="1" id='credit-amount' class="margin-input" name="credits"/>
            <input name="credit-submission" type="submit" class="submit" value="Send Credits" />
        </form>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>